language: go
go:
- 1.8

branches:
  only:
  - master

addons:
  apt:
    packages:
    - rsync
    - openssh-client

before_install:
- openssl aes-256-cbc -K $encrypted_63d3c23833fb_key -iv $encrypted_63d3c23833fb_iv -in travis_access.enc -out travis_access -d

install:
- GOPATH=$HOME/go go get github.com/gohugoio/hugo
- eval $(ssh-agent -s)
- chmod 600 travis_access && ssh-add travis_access
- mkdir -p ~/.ssh
- echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

script:
- "$HOME/go/bin/hugo"

after_success:
- rsync -avz --delete public/ $BLOG
